# docker-compose.yml
version: '3.8'

services:
  elixir:
    # build: .
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: iex
    tty: true
    stdin_open: true
